/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSinaisVitaisRouteImport } from './routes/_authenticated/sinais-vitais'
import { Route as AuthenticatedResidentesRouteImport } from './routes/_authenticated/residentes'
import { Route as AuthenticatedQuartosRouteImport } from './routes/_authenticated/quartos'
import { Route as AuthenticatedProntuarioRouteImport } from './routes/_authenticated/prontuario'
import { Route as AuthenticatedMedicamentosRouteImport } from './routes/_authenticated/medicamentos'
import { Route as AuthenticatedIncidentesRouteImport } from './routes/_authenticated/incidentes'
import { Route as AuthenticatedEvolucaoMultiRouteImport } from './routes/_authenticated/evolucao-multi'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChecklistsRouteImport } from './routes/_authenticated/checklists'
import { Route as AuthenticatedAdminAprovacoesRouteImport } from './routes/_authenticated/admin-aprovacoes'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSinaisVitaisRoute =
  AuthenticatedSinaisVitaisRouteImport.update({
    id: '/sinais-vitais',
    path: '/sinais-vitais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResidentesRoute = AuthenticatedResidentesRouteImport.update({
  id: '/residentes',
  path: '/residentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuartosRoute = AuthenticatedQuartosRouteImport.update({
  id: '/quartos',
  path: '/quartos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProntuarioRoute = AuthenticatedProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicamentosRoute =
  AuthenticatedMedicamentosRouteImport.update({
    id: '/medicamentos',
    path: '/medicamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentesRoute = AuthenticatedIncidentesRouteImport.update({
  id: '/incidentes',
  path: '/incidentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvolucaoMultiRoute =
  AuthenticatedEvolucaoMultiRouteImport.update({
    id: '/evolucao-multi',
    path: '/evolucao-multi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChecklistsRoute = AuthenticatedChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAprovacoesRoute =
  AuthenticatedAdminAprovacoesRouteImport.update({
    id: '/admin-aprovacoes',
    path: '/admin-aprovacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin-aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/checklists': typeof AuthenticatedChecklistsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evolucao-multi': typeof AuthenticatedEvolucaoMultiRoute
  '/incidentes': typeof AuthenticatedIncidentesRoute
  '/medicamentos': typeof AuthenticatedMedicamentosRoute
  '/prontuario': typeof AuthenticatedProntuarioRoute
  '/quartos': typeof AuthenticatedQuartosRoute
  '/residentes': typeof AuthenticatedResidentesRoute
  '/sinais-vitais': typeof AuthenticatedSinaisVitaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin-aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/checklists': typeof AuthenticatedChecklistsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evolucao-multi': typeof AuthenticatedEvolucaoMultiRoute
  '/incidentes': typeof AuthenticatedIncidentesRoute
  '/medicamentos': typeof AuthenticatedMedicamentosRoute
  '/prontuario': typeof AuthenticatedProntuarioRoute
  '/quartos': typeof AuthenticatedQuartosRoute
  '/residentes': typeof AuthenticatedResidentesRoute
  '/sinais-vitais': typeof AuthenticatedSinaisVitaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin-aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/_authenticated/checklists': typeof AuthenticatedChecklistsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/evolucao-multi': typeof AuthenticatedEvolucaoMultiRoute
  '/_authenticated/incidentes': typeof AuthenticatedIncidentesRoute
  '/_authenticated/medicamentos': typeof AuthenticatedMedicamentosRoute
  '/_authenticated/prontuario': typeof AuthenticatedProntuarioRoute
  '/_authenticated/quartos': typeof AuthenticatedQuartosRoute
  '/_authenticated/residentes': typeof AuthenticatedResidentesRoute
  '/_authenticated/sinais-vitais': typeof AuthenticatedSinaisVitaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando-aprovacao'
    | '/auth'
    | '/reset-password'
    | '/admin-aprovacoes'
    | '/checklists'
    | '/dashboard'
    | '/evolucao-multi'
    | '/incidentes'
    | '/medicamentos'
    | '/prontuario'
    | '/quartos'
    | '/residentes'
    | '/sinais-vitais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando-aprovacao'
    | '/auth'
    | '/reset-password'
    | '/admin-aprovacoes'
    | '/checklists'
    | '/dashboard'
    | '/evolucao-multi'
    | '/incidentes'
    | '/medicamentos'
    | '/prontuario'
    | '/quartos'
    | '/residentes'
    | '/sinais-vitais'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aguardando-aprovacao'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin-aprovacoes'
    | '/_authenticated/checklists'
    | '/_authenticated/dashboard'
    | '/_authenticated/evolucao-multi'
    | '/_authenticated/incidentes'
    | '/_authenticated/medicamentos'
    | '/_authenticated/prontuario'
    | '/_authenticated/quartos'
    | '/_authenticated/residentes'
    | '/_authenticated/sinais-vitais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sinais-vitais': {
      id: '/_authenticated/sinais-vitais'
      path: '/sinais-vitais'
      fullPath: '/sinais-vitais'
      preLoaderRoute: typeof AuthenticatedSinaisVitaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/residentes': {
      id: '/_authenticated/residentes'
      path: '/residentes'
      fullPath: '/residentes'
      preLoaderRoute: typeof AuthenticatedResidentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quartos': {
      id: '/_authenticated/quartos'
      path: '/quartos'
      fullPath: '/quartos'
      preLoaderRoute: typeof AuthenticatedQuartosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prontuario': {
      id: '/_authenticated/prontuario'
      path: '/prontuario'
      fullPath: '/prontuario'
      preLoaderRoute: typeof AuthenticatedProntuarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicamentos': {
      id: '/_authenticated/medicamentos'
      path: '/medicamentos'
      fullPath: '/medicamentos'
      preLoaderRoute: typeof AuthenticatedMedicamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidentes': {
      id: '/_authenticated/incidentes'
      path: '/incidentes'
      fullPath: '/incidentes'
      preLoaderRoute: typeof AuthenticatedIncidentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evolucao-multi': {
      id: '/_authenticated/evolucao-multi'
      path: '/evolucao-multi'
      fullPath: '/evolucao-multi'
      preLoaderRoute: typeof AuthenticatedEvolucaoMultiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklists': {
      id: '/_authenticated/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof AuthenticatedChecklistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-aprovacoes': {
      id: '/_authenticated/admin-aprovacoes'
      path: '/admin-aprovacoes'
      fullPath: '/admin-aprovacoes'
      preLoaderRoute: typeof AuthenticatedAdminAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAprovacoesRoute: typeof AuthenticatedAdminAprovacoesRoute
  AuthenticatedChecklistsRoute: typeof AuthenticatedChecklistsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEvolucaoMultiRoute: typeof AuthenticatedEvolucaoMultiRoute
  AuthenticatedIncidentesRoute: typeof AuthenticatedIncidentesRoute
  AuthenticatedMedicamentosRoute: typeof AuthenticatedMedicamentosRoute
  AuthenticatedProntuarioRoute: typeof AuthenticatedProntuarioRoute
  AuthenticatedQuartosRoute: typeof AuthenticatedQuartosRoute
  AuthenticatedResidentesRoute: typeof AuthenticatedResidentesRoute
  AuthenticatedSinaisVitaisRoute: typeof AuthenticatedSinaisVitaisRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAprovacoesRoute: AuthenticatedAdminAprovacoesRoute,
  AuthenticatedChecklistsRoute: AuthenticatedChecklistsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEvolucaoMultiRoute: AuthenticatedEvolucaoMultiRoute,
  AuthenticatedIncidentesRoute: AuthenticatedIncidentesRoute,
  AuthenticatedMedicamentosRoute: AuthenticatedMedicamentosRoute,
  AuthenticatedProntuarioRoute: AuthenticatedProntuarioRoute,
  AuthenticatedQuartosRoute: AuthenticatedQuartosRoute,
  AuthenticatedResidentesRoute: AuthenticatedResidentesRoute,
  AuthenticatedSinaisVitaisRoute: AuthenticatedSinaisVitaisRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
